# Generated by Django 3.0.3 on 2020-03-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDNB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=2048, null=True)),
                ('address_html', models.CharField(blank=True, max_length=2048, null=True)),
                ('website', models.CharField(blank=True, max_length=2048, null=True)),
                ('company_type', models.CharField(blank=True, max_length=2048, null=True)),
                ('company_role', models.CharField(blank=True, max_length=2048, null=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('employees', models.CharField(max_length=500)),
                ('incorporated', models.CharField(max_length=500)),
                ('corporate_family_connections', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'companies_dnb',
            },
        ),
        migrations.CreateModel(
            name='IndusryDNB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
            ],
            options={
                'db_table': 'industries_dnb',
            },
        ),
    ]
