# Generated by Django 3.0.3 on 2020-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb', '0003_shortcountrydnb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcountrydnb',
            name='country',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='shortcountrydnb',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
