# Generated by Django 3.0.3 on 2020-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb', '0004_auto_20200310_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydnb',
            name='link',
            field=models.CharField(blank=True, max_length=1500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companydnb',
            name='phone',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
