# Generated by Django 3.0.3 on 2020-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb', '0005_auto_20200310_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcountrydnb',
            name='country',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='shortcountrydnb',
            name='title',
            field=models.CharField(max_length=2500),
        ),
    ]
