# Generated by Django 3.0.3 on 2020-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb', '0007_auto_20200310_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydnb',
            name='corporate_family_connections',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companydnb',
            name='employees',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companydnb',
            name='incorporated',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
