# Generated by Django 3.0.3 on 2020-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb', '0008_auto_20200310_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydnb',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companydnb',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
