# Generated by Django 3.0.3 on 2020-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndeedCountrySites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2048, null=True)),
                ('site', models.CharField(blank=True, max_length=2048, null=True)),
                ('code_iso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'coutry_sites',
            },
        ),
    ]
