# Generated by Django 3.0.3 on 2020-03-31 10:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id_apollo', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
                ('number_of_employees', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tags', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apollo_company',
            },
        ),
        migrations.CreateModel(
            name='ApolloCompanyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
            ],
            options={
                'db_table': 'apollo_company_links',
            },
        ),
        migrations.CreateModel(
            name='ApolloTechUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=2048, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apollo.ApolloCompany')),
            ],
            options={
                'db_table': 'apollo_tech_used',
            },
        ),
        migrations.CreateModel(
            name='ApolloEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('position', models.CharField(blank=True, max_length=1024, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apollo.ApolloCompany')),
            ],
            options={
                'db_table': 'apollo_employees',
            },
        ),
    ]
