# Generated by Django 3.0.3 on 2020-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppoloCompanyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=2048, null=True, unique=True)),
            ],
            options={
                'db_table': 'apollo_company_links',
            },
        ),
    ]
