# Generated by Django 3.0.3 on 2020-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0002_apollocompany_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'apollo_tags',
            },
        ),
        migrations.RemoveField(
            model_name='apollocompany',
            name='tags',
        ),
        migrations.AddField(
            model_name='apollocompany',
            name='tags',
            field=models.ManyToManyField(to='apollo.ApolloTags'),
        ),
    ]
