# Generated by Django 3.0.3 on 2020-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0003_auto_20200401_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apollotags',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
