# Generated by Django 3.0.3 on 2020-03-02 16:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=str),
        ),
    ]
