# Generated by Django 3.0.3 on 2020-03-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancyaustralia_vacancycanada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancycanada',
            name='company',
        ),
        migrations.DeleteModel(
            name='VacancyAustralia',
        ),
        migrations.DeleteModel(
            name='VacancyCanada',
        ),
    ]
