# Generated by Django 3.0.3 on 2020-03-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=2048, null=True)),
                ('city', models.CharField(blank=True, max_length=2048, null=True)),
                ('code_state', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country_sites.IndeedCountrySites')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
