# Generated by Django 3.0.3 on 2020-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAustralia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('headquarters', models.TextField(blank=True, null=True)),
                ('employees', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('revenue', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies_australia',
            },
        ),
        migrations.CreateModel(
            name='CompanyCanada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('headquarters', models.TextField(blank=True, null=True)),
                ('employees', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('revenue', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies_canada',
            },
        ),
    ]
