# Generated by Django 3.0.3 on 2020-03-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20200321_2132'),
        ('companies', '0002_companyaustralia_companycanada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAustralia',
        ),
        migrations.DeleteModel(
            name='CompanyCanada',
        ),
    ]
