# Generated by Django 3.0.3 on 2020-03-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_sites', '0001_initial'),
        ('companies', '0003_auto_20200321_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country_sites.IndeedCountrySites'),
        ),
    ]
