# Generated by Django 3.0.3 on 2020-03-09 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLusha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('link_outer', models.CharField(blank=True, max_length=2048, null=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('company_details', django.contrib.postgres.fields.jsonb.JSONField(default=str)),
                ('company_social_networks', django.contrib.postgres.fields.jsonb.JSONField(default=str)),
                ('email_address_formats', django.contrib.postgres.fields.jsonb.JSONField(default=str)),
            ],
            options={
                'db_table': 'companies_lusha',
            },
        ),
    ]
